### ISSUE TITLE
rainbows

### ISSUE THREAD

**Issue by exekutive** [Sniper-E/fontawesome#3]
if you don't specify a color, the default is rainbow colors. Shouldn't it default to the color of normal post text.

**Comment by Sniper-E** [comment]
> 
> 
> if you don't specify a color, the default is rainbow colors. Shouldn't it default to the color of normal post text.

The color is not rainbow. It is, from the bottom, green, orange, red.
Look in ACP / Extensions tab / Font Awesome BBCode - Settings. Remove the color line...
background-image: linear-gradient(to top, green, orange, red) !important;-webkit-background-clip: text;color: transparent;
And put in color: initial or just leave that line blank.

**Comment by Sniper-E** [comment]
I posted in Github where you change that color in ACP Settings.

The newest version is on my site but it is not ready for release yet.
Login to my site to check it out if you want. tester/tester
https://www.sniper-e.com
